### PR TITLE
inc dependency versions

### PR DESCRIPTION
**Pull request by nk-coding**
inc all dependencies to latest stable if possible

### CODE REVIEW

**Comment by ModellbahnFreak** [comment]
Linux working.

Apple M1 Tbd

**Comment by snowball77** [comment]
If we use JDK17 should JavaFX not also stay on 17.x.x?

**Comment by nk-coding** [comment]
> As of JDK 11 the JavaFX modules are delivered separately from the JDK. These release notes cover the standalone JavaFX 18 release. JavaFX 18 requires JDK 11 or later.

Source: https://github.com/openjdk/jfx/blob/master/doc-files/release-notes-18.md
@snowball77

**Comment by snowball77** [comment]
I compiled it using the Intel macos MacBook and it compiled and tested ok.

**Review by snowball77 — APPROVED** [review]
From my side all looks good

**Review by ModellbahnFreak — APPROVED** [review]
I thingk we'll just ignore the M1 stuff and fix it if a student comes to us with problems

**Pull request merged**
