### PR TITLE
Refactor examples into real examples and teaching examples

### PR DESCRIPTION
**Pull request by snowball77**
This PR separates real API examples from examples used for teaching in the lecture.

### CODE REVIEW

**Comment by snowball77** [comment]
At least, the proposed state here is one I can use this week and next week in the lecture

**Comment by snowball77** [comment]
Any ideas or comments for improvements are more than welcome

**Comment by nk-coding** [comment]
I like the concept of separating, also the structure seems to be good.
However I still think that teaching examples should be put into an extra repository (maybe called sth like pse-hamster-examples or so?)

**Comment by snowball77** [comment]
> I like the concept of separating, also the structure seems to be good. However I still think that teaching examples should be put into an extra repository (maybe called sth like pse-hamster-examples or so?)

I can agree to that, maybe we do that in a second step and first merge it here? maybe the repo should be called pse-hamster-lecture?

**Comment by nk-coding** [comment]
fine for me

**Review by nk-coding — APPROVED** [review]

**Pull request merged**
